services:
  - type: web
    name: mi-api-habitos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FIREBASE_KEYS
        sync: false # Esto le dice a Render que el valor se manejar√° manualmente en el dashboard